### ISSUE TITLE
no longer tracking playtime

### ISSUE THREAD

**Issue by Fern-Leaves** [ma3a/SDH-PlayTime#70]
since the steamos update that was pushed to the stable channel just a few days ago this plugin has no longer tracked playtime, all previously recorded playtime is still displayed just fine, and the all time graph in settings is fine too, but the monthly, and weekly graphs don't load, and adding playtime manually doesn't do anything either.

**Comment by dshk0718** [comment]
This merge should fix this: https://github.com/ma3a/SDH-PlayTime/pull/63.
Here is the build for this: https://github.com/ma3a/SDH-PlayTime/pull/63#issuecomment-2350975345.

Download the Zip file and use the Decky Loader Developer menu to install the plugin from the zip file after uninstalling the existing plugin first.
Note that, while your past play time will still be intact, the play time of the games while the plugin wasn't working due to the compatibility issue with the new Decky API won't be there. That's what I noticed from my testing of this specific build.

If this build fixes your issue, you can go ahead and close this issue.

**Comment by p6002** [comment]
It hasn't worked for a long time, Decky supposedly a cool thing, but today I found out that half of the extensions don't work anymore and just make a garbage dump on Steam Deck.

**Comment by dshk0718** [comment]
@p6002 I hear you but you should remember that none of the developers who worked on these plugins are obligated to continue working on them since they are not getting paid to work on any of these plugins (that includes the developers for the Decky Loader itself as well). So I will just say that some of these plugins that come out on Decky may or may not "sunset" in a short amount of time after they come out. I definitely think it highly depends on the amount of the plugin usage and the plugin's main developer's free time.
However, with that said, since all of these projects (Decky Loader and its plugins) are open-source projects, if you can work on any of the issues that are brought up on either Decky or the plugins, I would highly suggest you work on them on your spare time.

**Comment by p6002** [comment]
I know what you mean, but if someone decides to dedicate their time to an open source project, they are not counting on monetising the project in advance. In addition, they should feel obliged to notify the current users that their project has been discontinued. Then no one would lose out and everyone would be happy.

**Comment by ma3a** [comment]
> they should 

Don't say what person should do, and I'll never heard where you should go. Simple as that.

Please guys go in DM for further discussion. After weekend trip I received a bunch of notifications that plugin stoped working. When I have a time I'll upload it, but not today.
